site_name: Knowledge Hub
theme:
  name: material
  palette:
    - scheme: slate  
      primary: indigo
      accent: cyan
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.snippets:
      base_path: ["docs"]

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

plugins:
  - search
  - gen-files:
      scripts:
        - gen_code_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

nav:
  - Home: index.md
  - Library:
      - Algorithms & Programming: uni-notes/pa/
      - Probability & Statistics: uni-notes/ps/
      - Systems & Networking: uni-notes/rc/
      - Operating Systems: uni-notes/so/
      - Data Structures: uni-notes/alo/