name: Update Submodules

on:
  schedule:
    - cron: '0 0 * * 0'  
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Update submodules
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git submodule update --remote --merge

      - name: Commit changes
        run: |
          if [[ -n $(git status -s) ]]; then
            git add -A
            git commit -m "chore: update submodules"
            git push origin main
          fi

      - name: Build and deploy
        run: |
          pip install mkdocs mkdocs-material mkdocs-gen-files mkdocs-literate-nav
          mkdocs gh-deploy --force